// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `RCISMousePicker.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __RCISMousePicker_h__
#define __RCISMousePicker_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompRCISMousePicker
{

class RCISMousePicker;
class RCISMousePickerPrx;

}

namespace RoboCompRCISMousePicker
{

struct Pick
{
    float x;
    float y;
    float z;
    ::std::string objectName;

    std::tuple<const float&, const float&, const float&, const ::std::string&> ice_tuple() const
    {
        return std::tie(x, y, z, objectName);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompRCISMousePicker
{

class RCISMousePicker : public virtual ::Ice::Object
{
public:

    using ProxyType = RCISMousePickerPrx;

    virtual bool ice_isA(::std::string, const ::Ice::Current&) const override;
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current&) const override;
    virtual ::std::string ice_id(const ::Ice::Current&) const override;

    static const ::std::string& ice_staticId();

    virtual void setPick(::RoboCompRCISMousePicker::Pick, const ::Ice::Current&) = 0;
    bool _iceD_setPick(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
};

}

namespace RoboCompRCISMousePicker
{

class RCISMousePickerPrx : public virtual ::Ice::Proxy<RCISMousePickerPrx, ::Ice::ObjectPrx>
{
public:

    void setPick(const ::RoboCompRCISMousePicker::Pick& iceP_myPick, const ::Ice::Context& context = Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &RoboCompRCISMousePicker::RCISMousePickerPrx::_iceI_setPick, iceP_myPick, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto setPickAsync(const ::RoboCompRCISMousePicker::Pick& iceP_myPick, const ::Ice::Context& context = Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &RoboCompRCISMousePicker::RCISMousePickerPrx::_iceI_setPick, iceP_myPick, context);
    }

    ::std::function<void()>
    setPickAsync(const ::RoboCompRCISMousePicker::Pick& iceP_myPick,
                 ::std::function<void()> response,
                 ::std::function<void(::std::exception_ptr)> ex = nullptr,
                 ::std::function<void(bool)> sent = nullptr,
                 const ::Ice::Context& context = Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &RoboCompRCISMousePicker::RCISMousePickerPrx::_iceI_setPick, iceP_myPick, context);
    }

    void _iceI_setPick(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::RoboCompRCISMousePicker::Pick&, const ::Ice::Context&);

    static const ::std::string& ice_staticId();

protected:

    RCISMousePickerPrx() = default;
    friend ::std::shared_ptr<RCISMousePickerPrx> IceInternal::createProxy<RCISMousePickerPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
};

}

namespace Ice
{

template<>
struct StreamableTraits<::RoboCompRCISMousePicker::Pick>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 13;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompRCISMousePicker::Pick, S>
{
    static void read(S* istr, ::RoboCompRCISMousePicker::Pick& v)
    {
        istr->readAll(v.x, v.y, v.z, v.objectName);
    }
};

}

namespace RoboCompRCISMousePicker
{

using RCISMousePickerPtr = ::std::shared_ptr<RCISMousePicker>;
using RCISMousePickerPrxPtr = ::std::shared_ptr<RCISMousePickerPrx>;

}

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompRCISMousePicker
{

class RCISMousePicker;
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompRCISMousePicker::RCISMousePicker>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompRCISMousePicker::RCISMousePicker*);

}

}

namespace RoboCompRCISMousePicker
{

class RCISMousePicker;
::Ice::Object* upCast(::RoboCompRCISMousePicker::RCISMousePicker*);
typedef ::IceInternal::Handle< ::RoboCompRCISMousePicker::RCISMousePicker> RCISMousePickerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompRCISMousePicker::RCISMousePicker> RCISMousePickerPrx;
typedef RCISMousePickerPrx RCISMousePickerPrxPtr;
void _icePatchObjectPtr(RCISMousePickerPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompRCISMousePicker
{

struct Pick
{
    ::Ice::Float x;
    ::Ice::Float y;
    ::Ice::Float z;
    ::std::string objectName;

    bool operator==(const Pick& rhs_) const
    {
        if(this == &rhs_)
        {
            return true;
        }
        if(x != rhs_.x)
        {
            return false;
        }
        if(y != rhs_.y)
        {
            return false;
        }
        if(z != rhs_.z)
        {
            return false;
        }
        if(objectName != rhs_.objectName)
        {
            return false;
        }
        return true;
    }

    bool operator<(const Pick& rhs_) const
    {
        if(this == &rhs_)
        {
            return false;
        }
        if(x < rhs_.x)
        {
            return true;
        }
        else if(rhs_.x < x)
        {
            return false;
        }
        if(y < rhs_.y)
        {
            return true;
        }
        else if(rhs_.y < y)
        {
            return false;
        }
        if(z < rhs_.z)
        {
            return true;
        }
        else if(rhs_.z < z)
        {
            return false;
        }
        if(objectName < rhs_.objectName)
        {
            return true;
        }
        else if(rhs_.objectName < objectName)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const Pick& rhs_) const
    {
        return !operator==(rhs_);
    }
    bool operator<=(const Pick& rhs_) const
    {
        return operator<(rhs_) || operator==(rhs_);
    }
    bool operator>(const Pick& rhs_) const
    {
        return !operator<(rhs_) && !operator==(rhs_);
    }
    bool operator>=(const Pick& rhs_) const
    {
        return !operator<(rhs_);
    }
};

}

namespace RoboCompRCISMousePicker
{

class Callback_RCISMousePicker_setPick_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_RCISMousePicker_setPick_Base> Callback_RCISMousePicker_setPickPtr;

}

namespace IceProxy
{

namespace RoboCompRCISMousePicker
{

class RCISMousePicker : public virtual ::Ice::Proxy<RCISMousePicker, ::IceProxy::Ice::Object>
{
public:

    void setPick(const ::RoboCompRCISMousePicker::Pick& iceP_myPick, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_setPick(_iceI_begin_setPick(iceP_myPick, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_setPick(const ::RoboCompRCISMousePicker::Pick& iceP_myPick, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_setPick(iceP_myPick, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setPick(const ::RoboCompRCISMousePicker::Pick& iceP_myPick, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setPick(iceP_myPick, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setPick(const ::RoboCompRCISMousePicker::Pick& iceP_myPick, const ::Ice::Context& context, const ::Ice::CallbackPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setPick(iceP_myPick, context, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setPick(const ::RoboCompRCISMousePicker::Pick& iceP_myPick, const ::RoboCompRCISMousePicker::Callback_RCISMousePicker_setPickPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setPick(iceP_myPick, ::Ice::noExplicitContext, del, cookie);
    }

    ::Ice::AsyncResultPtr begin_setPick(const ::RoboCompRCISMousePicker::Pick& iceP_myPick, const ::Ice::Context& context, const ::RoboCompRCISMousePicker::Callback_RCISMousePicker_setPickPtr& del, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_setPick(iceP_myPick, context, del, cookie);
    }

    void end_setPick(const ::Ice::AsyncResultPtr&);

private:

    ::Ice::AsyncResultPtr _iceI_begin_setPick(const ::RoboCompRCISMousePicker::Pick&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    static const ::std::string& ice_staticId();

protected:

    virtual ::IceProxy::Ice::Object* _newInstance() const;
};

}

}

namespace RoboCompRCISMousePicker
{

class RCISMousePicker : public virtual ::Ice::Object
{
public:

    typedef RCISMousePickerPrx ProxyType;
    typedef RCISMousePickerPtr PointerType;

    virtual ~RCISMousePicker();

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::emptyCurrent) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::emptyCurrent) const;

    static const ::std::string& ice_staticId();

    virtual void setPick(const ::RoboCompRCISMousePicker::Pick&, const ::Ice::Current& = ::Ice::emptyCurrent) = 0;
    bool _iceD_setPick(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:

    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
};

inline bool operator==(const RCISMousePicker& lhs, const RCISMousePicker& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const RCISMousePicker& lhs, const RCISMousePicker& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}

}

namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompRCISMousePicker::Pick>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 13;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompRCISMousePicker::Pick, S>
{
    static void write(S* ostr, const ::RoboCompRCISMousePicker::Pick& v)
    {
        ostr->write(v.x);
        ostr->write(v.y);
        ostr->write(v.z);
        ostr->write(v.objectName);
    }
};

template<typename S>
struct StreamReader< ::RoboCompRCISMousePicker::Pick, S>
{
    static void read(S* istr, ::RoboCompRCISMousePicker::Pick& v)
    {
        istr->read(v.x);
        istr->read(v.y);
        istr->read(v.z);
        istr->read(v.objectName);
    }
};

}

namespace RoboCompRCISMousePicker
{

template<class T>
class CallbackNC_RCISMousePicker_setPick : public Callback_RCISMousePicker_setPick_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_RCISMousePicker_setPick(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_RCISMousePicker_setPickPtr
newCallback_RCISMousePicker_setPick(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RCISMousePicker_setPick<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RCISMousePicker_setPickPtr
newCallback_RCISMousePicker_setPick(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RCISMousePicker_setPick<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_RCISMousePicker_setPickPtr
newCallback_RCISMousePicker_setPick(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RCISMousePicker_setPick<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RCISMousePicker_setPickPtr
newCallback_RCISMousePicker_setPick(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RCISMousePicker_setPick<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_RCISMousePicker_setPick : public Callback_RCISMousePicker_setPick_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_RCISMousePicker_setPick(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_RCISMousePicker_setPickPtr
newCallback_RCISMousePicker_setPick(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RCISMousePicker_setPick<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RCISMousePicker_setPickPtr
newCallback_RCISMousePicker_setPick(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RCISMousePicker_setPick<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_RCISMousePicker_setPickPtr
newCallback_RCISMousePicker_setPick(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RCISMousePicker_setPick<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RCISMousePicker_setPickPtr
newCallback_RCISMousePicker_setPick(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RCISMousePicker_setPick<T, CT>(instance, 0, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
